enum GraphQLErrorCode {
  SYNTAX_ERROR = 'GRAPHQL_PARSE_FAILED',
  VALIDATION_ERROR = 'GRAPHQL_VALIDATION_FAILED',
  USER_INPUT_ERROR = 'BAD_USER_INPUT',
  AUTHENTICATION_ERROR = 'UNAUTHENTICATED',
  FORBIDDEN_ERROR = 'FORBIDDEN',
  PERSISTED_QUERY_NOT_FOUND_ERROR = 'PERSISTED_QUERY_NOT_FOUND',
  PERSISTED_QUERY_NOT_SUPPORTED_ERROR = 'PERSISTED_QUERY_NOT_SUPPORTED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export { GraphQLErrorCode };
